services:
  web:
    build: .
    image: py-intercom-web
    container_name: py-intercom-web
    restart: unless-stopped
    network_mode: host
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8443"
      - "--ssl-adhoc"
