version: "3.9"

services:
  web:
    image: ghcr.io/lfpoulain/py-intercom-web:latest
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: unless-stopped
    ports:
      - "${PY_INTERCOM_WEB_PORT:-8741}:${PY_INTERCOM_WEB_PORT:-8741}"
      - "${PY_INTERCOM_DISCOVERY_PORT:-5002}:5002/udp"
    environment:
      PY_INTERCOM_WEB_HOST: 0.0.0.0
      PY_INTERCOM_WEB_PORT: ${PY_INTERCOM_WEB_PORT:-8741}
      PY_INTERCOM_WEB_DEBUG: ${PY_INTERCOM_WEB_DEBUG:-0}
      PY_INTERCOM_WEB_SSL_MODE: ${PY_INTERCOM_WEB_SSL_MODE:-plain}
