services:
  py-intercom-web:
    build:
      context: ..
      dockerfile: docker/web/Dockerfile
    container_name: py-intercom-web
    restart: unless-stopped
    environment:
      GITEA_REPO_URL: "http://10.0.0.4:3000/lfpoulain/py-intercom.git"
      APP_DIR: "/opt/py-intercom"
      WEB_PORT: "8443"
    ports:
      - "8443:8443"
      - "5002:5002/udp"
    volumes:
      - py_intercom_web_repo:/opt/py-intercom

volumes:
  py_intercom_web_repo:
